{
 "title": "Nginx Overview",
 "tags": [
  "provisioned",
  "nginx",
  "exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nginx_up{job=\"nginx\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx exporter status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{job=\"nginx\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} RPS"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"nginx\",instance=~\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Connection states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "nginx_connections_reading{job=\"nginx\",instance=~\"$instance\"}",
     "legendFormat": "reading"
    },
    {
     "expr": "nginx_connections_writing{job=\"nginx\",instance=~\"$instance\"}",
     "legendFormat": "writing"
    },
    {
     "expr": "nginx_connections_waiting{job=\"nginx\",instance=~\"$instance\"}",
     "legendFormat": "waiting"
    }
   ]
  }
 ]
}